### ISSUE TITLE
It's asking me to enter a credit card for Heroku?

### ISSUE THREAD

**Issue by NateMorgan** [butttons/clash-caller#1]
Gives me this when I follow the steps, is this normal, or does the usage never get above the free version?

Nathaniels-MacBook-Pro:caller-bot NathanielRMorgan$ heroku addons:create cleardb:ignite
 !    Please verify your account to install this add-on plan (please enter a credit card) For more information, see https://devcenter.heroku.com/categories/billing Verify now at https://heroku.com/verify 
Nathaniels-MacBook-Pro:caller-bot NathanielRMorgan$

**Comment by butttons** [comment]
Yes, you need to add a credit card to heroku, for verification purposes. The addon and hosting are free, so you won't be charged.
